id: A1237D6E2
title: Guru Yoga Focusing upon Noble Kurukullā
type: translation
pechas:
- IBF0FD209
- I5A552349
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:42.235294
  last_modified_at: 2023-01-04 13:08:42.235303
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBF0FD209/A58B: '0454'
  I5A552349/D8DB: '0454'
